// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node scripts/dev/seed.js", // prisma db seed で開発データ投入
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
